### ISSUE TITLE
set_key_entry creates unstorable keystore

### ISSUE THREAD

**Issue by danleyden** [rylarson/keystores#3]
I believe that the following should result in a valid jks format keystore:

```
require 'openssl'
require 'keystores'

identity_key = OpenSSL::PKey::RSA.new(File.read('key.pem'))
identity_cert = OpenSSL::X509::Certificate.new(File.read('cert.pem'))

keystore = OpenSSL::JKS.new
keystore.set_key_entry('my_key', key, cert, 'password')
keystore.store '/tmp/keys.jks', 'password'
```

Instead, I get a failure when calling `keystore.store` with `lib/keystores/java_key_store.rb:226:in `block (2 levels) in store': undefined method `length' for #<OpenSSL::X509::Certificate:0x007fb7e3848a08> (NoMethodError)`

**Comment by rylarson** [comment]
Closed by #4
